server:
   port: 8080
logging:
   config: classpath:logback-spring.xml
spring:
   datasource:
      url: jdbc:mysql://129.204.99.160:3306/wecube_dev?useUnicode=true&characterEncoding=UTF8&useJDBCTCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      username: wecube
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
   profiles:
      active: dev
   thymeleaf:
      cache: false